In [2]:
import numpy as np

In [4]:
rev_1=np.array([10,20,30])

In [3]:
rev_1

array([10, 20, 30])

In [5]:
rev_1.ndim #used to get dimension

1

In [6]:
rev_2=np.array([[10,20,30],[40,50,60]])   #this is a 2 dimension array
rev_2

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
rev_2[1,1] # it is used to get the value at that point 

50

In [8]:
#But if we want to change a value at that particular dimension, we can do this
rev_2[1,1]=100
rev_2

array([[ 10,  20,  30],
       [ 40, 100,  60]])

In [9]:
# to get the type
rev_2.dtype

dtype('int32')

In [10]:
#If we want to change the data type we can do like this
rev_2=np.array([[10,20,30],[40,50,60]], dtype=np.float64)
rev_2.dtype
#we can do float8, float16, float64, depending upon our requirement , as 1byte=8bits , so if we want 2 byte we will use float16

dtype('float64')

In [11]:
# to get the no of rows and columns 
rev_2.shape

(2, 3)

In [13]:
#to sort the elements
np.sort(rev_1)

array([10, 20, 30])

In [17]:
#In 2D array if we want to sort it and arrange it in a linear way we use keyword axis=None
np.sort(rev_2, axis=None)

array([10., 20., 30., 40., 50., 60.])

In [19]:
#If we want to create a array of zeros and ones 
np.ones((2,2))


array([[1., 1.],
       [1., 1.]])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
#to create a array 
np.arange(3)

array([0, 1, 2])

In [22]:
#to create a array between the numbers 10 to 20 
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
#to create a array of step size 2 
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [24]:
#if we want to make equal parts of a number range , ex make 3 equal parts of range from 10 to 20
np.linspace(10,20,3)

array([10., 15., 20.])

In [25]:
#If u want to make 2d array into linear array , there are two methods ravel and flatten 
#ravel =If you change the original array, the raveled one might change too.
#flatten= Always creates a new array, Safe to use if you want to keep the original array unchanged



In [28]:
rev_2.ravel()

array([10., 20., 30., 40., 50., 60.])

In [29]:
rev_2.flatten()

array([10., 20., 30., 40., 50., 60.])

In [38]:
# to reshape a array
rev_2.reshape(2,3)

array([[10., 20., 30.],
       [40., 50., 60.]])

In [36]:
#to find min and max
rev_2.min()



10.0

In [39]:
# if we want to do sum horizonatally of each row
rev_2.sum(axis=1)

array([ 60., 150.])

In [40]:
rev_2.sum(axis=0)

array([50., 70., 90.])

In [42]:
for row in rev_2:
    print("row=", row)

row= [10. 20. 30.]
row= [40. 50. 60.]


In [47]:
#to find the square root
b=np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [48]:
#to find the squares
np.square(b)

array([  1,  16, 256])

In [49]:
#to find the standard deviation
np.std(b)

6.48074069840786

In [6]:
#rows represnt different products and columns represnts different regions (usa , india , china)
q1=np.array([
    [200,220,250],#iphone
    [150,180,210],#ipad
    [300,330,360]#macbook 
])

q2=np.array([
[209,231,259],
[155,192,222],
[310,340,375]
])

In [7]:
q1+q2 # combined sales from both the countries

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [8]:
# if u want to find how much more percent wise did q2 have more sales than q1
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [12]:
#If I want to find revenue
prices=np.array([
    [10,12,11],
    [8,9,10],
    [15,16,17]
])
q1_revenue=prices*q1
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [14]:
#if i have given discount of 20% , then total revenue is 
q1_discount=q1_revenue*0.2
total_rev=q1_revenue-q1_discount
total_rev

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [16]:
#if we want to multiple, add matrix wise entity like 1 element multipled bby 1st element , 2nd element multiplied by 2nd element 
#we use dot product
features=np.array([
    [2000,3],#house 1
    [1800,2]#house 2
])

weights=np.array([150,50000])
np.dot(features,weights)

array([450000, 370000])

In [33]:
a=np.array([1,2,3,4,5])

In [35]:
#We cannot access 1 dimensional array backwards but we can access the 2d array backwards

In [37]:
a=np.array([[1,2,3,4,5],
           [6,7,8,9,10]
           ])

In [40]:
a[-1,1:3]

array([7, 8])

In [41]:
a=np.array([[1, 2, 3],
           [6,  7, 8 ],
           [17,18, 19]
           ])

In [43]:
#if I want only the last 2 columns, ":" beacuse i want all the rows 
a[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [18, 19]])

In [5]:
#customer id , name
c=np.array([[101,'Mira'],
          [102,'Abdul'],
           [103,'Andrea']
           ])
#customer id, purchase amt, purchase date
d=np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01'],
])


In [7]:
np.hstack((c,d)) #to add everything all together

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [8]:
#if we want to add more 
e=np.array([
    [104,'venkat'],
    [105,'john'],
    [106,'srushti']
])


In [10]:
np.vstack((c,e)) #v means vertically stack

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'venkat'],
       ['105', 'john'],
       ['106', 'srushti']], dtype='<U11')

In [11]:
transactions=np.array([
    ['mira',101, 250.50, '2023-08-01'],
    ['subodh',102, 150.00, '2023-08-02'],
    ['mishra',103, 300.75, '2023-08-01'],
])

In [12]:
#if we want to split horizontally 
np.hsplit(transactions,[3]) 

[array([['mira', '101', '250.5'],
        ['subodh', '102', '150.0'],
        ['mishra', '103', '300.75']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01']], dtype='<U32')]

In [13]:
#if we want to store the horizontally split amount in 2 containers 
a,b=np.hsplit(transactions,[3]) 

In [14]:
a

array([['mira', '101', '250.5'],
       ['subodh', '102', '150.0'],
       ['mishra', '103', '300.75']], dtype='<U32')

In [15]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01']], dtype='<U32')

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(1,5,3)

array([1., 3., 5.])